services:
  easy-diff:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "service nginx start && ./start.sh" 
    image: easy-diff:3.0.1
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TZ=Europe/Moscow
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    container_name: easy-diff
    ports:
      - "8080:8080"
    volumes:
      # - /home/$USER/easy-diff-models/:/stablediff/models/stable-diffusion/
      - ${HOST_PATH_MODELS}:/stablediff/models/